import json

# class stringconvert() :

result2 = ''' {
  "results": [
    {
      "alternatives": [
        {
          "word_confidence": [
            [
              "my",
              0.785
            ],
            [
              "name's",
              0.739
            ],
            [
              "Matt",
              0.805
            ],
            [
              "and",
              0.971
            ],
            [
              "I'm",
              0.539
            ],
            [
              "gonna",
              0.51
            ],
            [
              "be",
              0.66
            ],
            [
              "your",
              0.78
            ],
            [
              "interviewer",
              0.34
            ],
            [
              "for",
              0.837
            ],
            [
              "today",
              0.997
            ],
            [
              "so",
              1.0
            ],
            [
              "please",
              0.984
            ],
            [
              "%HESITATION",
              0.705
            ],
            [
              "tell",
              1.0
            ],
            [
              "me",
              1.0
            ],
            [
              "a",
              0.732
            ],
            [
              "little",
              1.0
            ],
            [
              "bit",
              1.0
            ],
            [
              "about",
              1.0
            ],
            [
              "yourself",
              0.984
            ]
          ],
          "confidence": 0.825,
          "transcript": "my name's Matt and I'm gonna be your interviewer for today so please %HESITATION tell me a little bit about yourself ",
          "timestamps": [
            [
              "my",
              0.2,
              0.42
            ],
            [
              "name's",
              0.42,
              0.71
            ],
            [
              "Matt",
              0.71,
              1.05
            ],
            [
              "and",
              1.05,
              1.18
            ],
            [
              "I'm",
              1.18,
              1.27
            ],
            [
              "gonna",
              1.27,
              1.42
            ],
            [
              "be",
              1.42,
              1.52
            ],
            [
              "your",
              1.52,
              1.67
            ],
            [
              "interviewer",
              1.67,
              2.15
            ],
            [
              "for",
              2.15,
              2.34
            ],
            [
              "today",
              2.34,
              2.75
            ],
            [
              "so",
              3.25,
              3.54
            ],
            [
              "please",
              3.54,
              4.15
            ],
            [
              "%HESITATION",
              4.15,
              4.7
            ],
            [
              "tell",
              5.22,
              5.41
            ],
            [
              "me",
              5.41,
              5.52
            ],
            [
              "a",
              5.52,
              5.58
            ],
            [
              "little",
              5.58,
              5.76
            ],
            [
              "bit",
              5.76,
              5.85
            ],
            [
              "about",
              5.85,
              6.03
            ],
            [
              "yourself",
              6.03,
              6.48
            ]
          ]
        }
      ],
      "final": true
    },
    {
      "alternatives": [
        {
          "word_confidence": [
            [
              "yeah",
              0.367
            ],
            [
              "and",
              1.0
            ],
            [
              "I'm",
              0.896
            ],
            [
              "going",
              0.545
            ],
            [
              "to",
              0.507
            ],
            [
              "be",
              0.675
            ],
            [
              "a",
              0.155
            ],
            [
              "junior",
              0.91
            ],
            [
              "at",
              1.0
            ],
            [
              "UC",
              1.0
            ],
            [
              "Berkeley",
              0.908
            ],
            [
              "all",
              0.908
            ],
            [
              "and",
              0.97
            ],
            [
              "currently",
              0.894
            ],
            [
              "I'm",
              0.822
            ],
            [
              "studying",
              1.0
            ],
            [
              "computer",
              1.0
            ],
            [
              "science",
              1.0
            ],
            [
              "and",
              0.893
            ]
          ],
          "confidence": 0.863,
          "transcript": "yeah and I'm going to be a junior at UC Berkeley all and currently I'm studying computer science and ",
          "timestamps": [
            [
              "yeah",
              8.59,
              8.97
            ],
            [
              "and",
              9.0,
              9.33
            ],
            [
              "I'm",
              9.33,
              9.48
            ],
            [
              "going",
              9.48,
              9.6
            ],
            [
              "to",
              9.6,
              9.67
            ],
            [
              "be",
              9.67,
              9.99
            ],
            [
              "a",
              10.26,
              10.31
            ],
            [
              "junior",
              10.31,
              10.68
            ],
            [
              "at",
              10.68,
              10.77
            ],
            [
              "UC",
              10.77,
              11.04
            ],
            [
              "Berkeley",
              11.04,
              11.44
            ],
            [
              "all",
              11.66,
              12.11
            ],
            [
              "and",
              12.15,
              12.55
            ],
            [
              "currently",
              12.55,
              13.03
            ],
            [
              "I'm",
              13.03,
              13.3
            ],
            [
              "studying",
              13.3,
              13.64
            ],
            [
              "computer",
              13.64,
              13.96
            ],
            [
              "science",
              13.96,
              14.31
            ],
            [
              "and",
              14.31,
              14.56
            ]
          ]
        }
      ],
      "final": true
    },
    {
      "alternatives": [
        {
          "word_confidence": [
            [
              "great",
              1.0
            ],
            [
              "next",
              1.0
            ],
            [
              "question",
              1.0
            ],
            [
              "why",
              0.886
            ],
            [
              "do",
              0.738
            ],
            [
              "you",
              1.0
            ],
            [
              "want",
              0.836
            ],
            [
              "to",
              0.836
            ],
            [
              "work",
              1.0
            ],
            [
              "for",
              1.0
            ],
            [
              "IBM",
              0.994
            ]
          ],
          "confidence": 0.973,
          "transcript": "great next question why do you want to work for IBM ",
          "timestamps": [
            [
              "great",
              15.47,
              15.85
            ],
            [
              "next",
              15.88,
              16.23
            ],
            [
              "question",
              16.23,
              16.82
            ],
            [
              "why",
              17.04,
              17.23
            ],
            [
              "do",
              17.23,
              17.3
            ],
            [
              "you",
              17.3,
              17.37
            ],
            [
              "want",
              17.37,
              17.52
            ],
            [
              "to",
              17.52,
              17.58
            ],
            [
              "work",
              17.58,
              17.87
            ],
            [
              "for",
              17.87,
              18.02
            ],
            [
              "IBM",
              18.02,
              18.64
            ]
          ]
        }
      ],
      "final": true
    },
    {
      "alternatives": [
        {
          "word_confidence": [
            [
              "IBM's",
              0.145
            ],
            [
              "progressive",
              0.404
            ],
            [
              "work",
              0.779
            ],
            [
              "ethic",
              0.227
            ],
            [
              "with",
              0.929
            ],
            [
              "their",
              1.0
            ],
            [
              "new",
              1.0
            ],
            [
              "ads",
              0.346
            ],
            [
              "on",
              0.157
            ],
            [
              "methodology",
              0.98
            ]
          ],
          "confidence": 0.59,
          "transcript": "IBM's progressive work ethic with their new ads on methodology ",
          "timestamps": [
            [
              "IBM's",
              20.52,
              21.01
            ],
            [
              "progressive",
              21.01,
              21.52
            ],
            [
              "work",
              21.58,
              21.86
            ],
            [
              "ethic",
              21.86,
              22.23
            ],
            [
              "with",
              22.26,
              22.46
            ],
            [
              "their",
              22.46,
              22.62
            ],
            [
              "new",
              22.62,
              22.93
            ],
            [
              "ads",
              22.93,
              23.33
            ],
            [
              "on",
              23.33,
              23.54
            ],
            [
              "methodology",
              23.54,
              24.37
            ]
          ]
        }
      ],
      "final": true
    },
    {
      "alternatives": [
        {
          "word_confidence": [
            [
              "I",
              1.0
            ],
            [
              "think",
              0.984
            ],
            [
              "it",
              0.802
            ],
            [
              "would",
              0.822
            ],
            [
              "really",
              0.998
            ],
            [
              "help",
              0.883
            ],
            [
              "with",
              0.481
            ],
            [
              "working",
              0.897
            ],
            [
              "on",
              0.901
            ],
            [
              "different",
              0.588
            ],
            [
              "projects",
              0.982
            ],
            [
              "awesome",
              0.506
            ],
            [
              "next",
              1.0
            ],
            [
              "question",
              0.994
            ],
            [
              "what",
              0.84
            ],
            [
              "are",
              0.994
            ],
            [
              "some",
              1.0
            ],
            [
              "of",
              0.829
            ],
            [
              "your",
              1.0
            ],
            [
              "strengths",
              0.995
            ]
          ],
          "confidence": 0.878,
          "transcript": "I think it would really help with working on different projects awesome next question what are some of your strengths ",
          "timestamps": [
            [
              "I",
              25.57,
              25.69
            ],
            [
              "think",
              25.69,
              25.94
            ],
            [
              "it",
              25.94,
              26.04
            ],
            [
              "would",
              26.04,
              26.33
            ],
            [
              "really",
              26.33,
              26.66
            ],
            [
              "help",
              26.66,
              26.92
            ],
            [
              "with",
              26.92,
              27.04
            ],
            [
              "working",
              27.04,
              27.32
            ],
            [
              "on",
              27.32,
              27.43
            ],
            [
              "different",
              27.43,
              27.68
            ],
            [
              "projects",
              27.68,
              28.28
            ],
            [
              "awesome",
              28.61,
              29.27
            ],
            [
              "next",
              29.3,
              29.62
            ],
            [
              "question",
              29.62,
              30.3
            ],
            [
              "what",
              30.91,
              31.15
            ],
            [
              "are",
              31.15,
              31.23
            ],
            [
              "some",
              31.23,
              31.43
            ],
            [
              "of",
              31.43,
              31.5
            ],
            [
              "your",
              31.5,
              31.63
            ],
            [
              "strengths",
              31.63,
              32.33
            ]
          ]
        }
      ],
      "final": true
    },
    {
      "alternatives": [
        {
          "word_confidence": [
            [
              "I'm",
              0.572
            ],
            [
              "very",
              0.984
            ],
            [
              "posh",
              0.417
            ],
            [
              "about",
              0.556
            ],
            [
              "my",
              0.971
            ],
            [
              "work",
              0.51
            ],
            [
              "and",
              0.988
            ],
            [
              "I",
              0.767
            ],
            [
              "love",
              0.249
            ],
            [
              "working",
              0.983
            ],
            [
              "in",
              1.0
            ],
            [
              "a",
              1.0
            ],
            [
              "team",
              1.0
            ],
            [
              "environment",
              0.991
            ],
            [
              "great",
              0.658
            ],
            [
              "next",
              0.967
            ],
            [
              "question",
              1.0
            ],
            [
              "what",
              1.0
            ],
            [
              "did",
              0.812
            ],
            [
              "you",
              0.953
            ],
            [
              "do",
              0.966
            ],
            [
              "in",
              0.387
            ],
            [
              "your",
              1.0
            ],
            [
              "last",
              1.0
            ],
            [
              "job",
              0.986
            ]
          ],
          "confidence": 0.816,
          "transcript": "I'm very posh about my work and I love working in a team environment great next question what did you do in your last job ",
          "timestamps": [
            [
              "I'm",
              33.24,
              33.49
            ],
            [
              "very",
              33.49,
              33.78
            ],
            [
              "posh",
              33.78,
              34.14
            ],
            [
              "about",
              34.14,
              34.37
            ],
            [
              "my",
              34.37,
              34.48
            ],
            [
              "work",
              34.48,
              34.87
            ],
            [
              "and",
              34.9,
              35.03
            ],
            [
              "I",
              35.03,
              35.1
            ],
            [
              "love",
              35.1,
              35.46
            ],
            [
              "working",
              35.46,
              35.79
            ],
            [
              "in",
              35.79,
              35.89
            ],
            [
              "a",
              35.89,
              35.98
            ],
            [
              "team",
              35.98,
              36.26
            ],
            [
              "environment",
              36.26,
              36.77
            ],
            [
              "great",
              37.38,
              37.73
            ],
            [
              "next",
              37.73,
              38.07
            ],
            [
              "question",
              38.07,
              38.63
            ],
            [
              "what",
              38.83,
              39.01
            ],
            [
              "did",
              39.01,
              39.13
            ],
            [
              "you",
              39.13,
              39.25
            ],
            [
              "do",
              39.25,
              39.39
            ],
            [
              "in",
              39.39,
              39.5
            ],
            [
              "your",
              39.5,
              39.63
            ],
            [
              "last",
              39.63,
              39.97
            ],
            [
              "job",
              39.97,
              40.35
            ]
          ]
        }
      ],
      "final": true
    },
    {
      "alternatives": [
        {
          "word_confidence": [
            [
              "I",
              1.0
            ],
            [
              "use",
              0.994
            ],
            [
              "react",
              0.475
            ],
            [
              "and",
              0.825
            ],
            [
              "open",
              0.777
            ],
            [
              "source",
              0.628
            ],
            [
              "component",
              0.761
            ],
            [
              "libraries",
              1.0
            ],
            [
              "to",
              1.0
            ],
            [
              "create",
              1.0
            ],
            [
              "responsive",
              0.425
            ],
            [
              "on",
              0.892
            ],
            [
              "and",
              0.944
            ]
          ],
          "confidence": 0.795,
          "transcript": "I use react and open source component libraries to create responsive on and ",
          "timestamps": [
            [
              "I",
              41.15,
              41.3
            ],
            [
              "use",
              41.3,
              41.78
            ],
            [
              "react",
              41.78,
              42.38
            ],
            [
              "and",
              42.41,
              42.7
            ],
            [
              "open",
              42.7,
              42.96
            ],
            [
              "source",
              42.96,
              43.21
            ],
            [
              "component",
              43.21,
              43.66
            ],
            [
              "libraries",
              43.66,
              44.26
            ],
            [
              "to",
              44.26,
              44.43
            ],
            [
              "create",
              44.43,
              44.86
            ],
            [
              "responsive",
              44.86,
              45.39
            ],
            [
              "on",
              45.45,
              45.68
            ],
            [
              "and",
              45.71,
              46.02
            ]
          ]
        }
      ],
      "final": true
    },
    {
      "alternatives": [
        {
          "word_confidence": [
            [
              "thanks",
              0.468
            ],
            [
              "I",
              0.07
            ],
            [
              "was",
              0.07
            ],
            [
              "made",
              0.359
            ],
            [
              "up",
              0.362
            ],
            [
              "will",
              0.551
            ],
            [
              "let",
              0.976
            ],
            [
              "you",
              1.0
            ],
            [
              "know",
              0.825
            ],
            [
              "in",
              0.632
            ],
            [
              "about",
              0.982
            ],
            [
              "a",
              1.0
            ],
            [
              "week",
              0.992
            ]
          ],
          "confidence": 0.696,
          "transcript": "thanks I was made up will let you know in about a week ",
          "timestamps": [
            [
              "thanks",
              47.27,
              47.55
            ],
            [
              "I",
              47.55,
              47.59
            ],
            [
              "was",
              47.59,
              47.71
            ],
            [
              "made",
              47.71,
              47.9
            ],
            [
              "up",
              47.9,
              48.08
            ],
            [
              "will",
              48.11,
              48.25
            ],
            [
              "let",
              48.25,
              48.4
            ],
            [
              "you",
              48.4,
              48.53
            ],
            [
              "know",
              48.53,
              48.7
            ],
            [
              "in",
              48.7,
              48.78
            ],
            [
              "about",
              48.78,
              49.04
            ],
            [
              "a",
              49.04,
              49.1
            ],
            [
              "week",
              49.1,
              49.5
            ]
          ]
        }
      ],
      "final": true
    },
    {
      "alternatives": [
        {
          "word_confidence": [
            [
              "I",
              0.641
            ]
          ],
          "confidence": 0.641,
          "transcript": "I ",
          "timestamps": [
            [
              "I",
              50.1,
              50.41
            ]
          ]
        }
      ],
      "final": true
    }
  ],
  "result_index": 0
}
'''


result =  '''{
    "results": [
        {
        "alternatives": [
            {
            "word_confidence": [
                [
                "several", 
                1.0
                ], 
                [
                "tornadoes", 
                1.0
                ], 
                [
                "touch", 
                0.515
                ], 
                [
                "down", 
                0.916
                ], 
                [
                "as", 
                0.314
                ], 
                [
                "a", 
                0.539
                ], 
                [
                "line", 
                1.0
                ], 
                [
                "of", 
                1.0
                ], 
                [
                "severe", 
                1.0
                ], 
                [
                "thunderstorms", 
                0.758
                ], 
                [
                "swept", 
                1.0
                ], 
                [
                "through", 
                1.0
                ], 
                [
                "Colorado", 
                0.989
                ], 
                [
                "on", 
                0.369
                ], 
                [
                "Sunday", 
                0.978
                ]
            ], 
            "confidence": 0.889, 
            "transcript": "Hi I'm Matt and I will be interviewing you Tell me about yourself I go to Berkeley Next question What are your strengths", 
            "timestamps": [
                [
                "several", 
                1.0, 
                1.52
                ], 
                [
                "tornadoes", 
                1.52, 
                2.15
                ], 
                [
                "touch", 
                2.15, 
                2.49
                ], 
                [
                "down", 
                2.49, 
                2.82
                ], 
                [
                "as", 
                2.82, 
                2.92
                ], 
                [
                "a", 
                2.92, 
                3.01
                ], 
                [
                "line", 
                3.01, 
                3.3
                ], 
                [
                "of", 
                3.3, 
                3.39
                ], 
                [
                "severe", 
                3.39, 
                3.77
                ], 
                [
                "thunderstorms", 
                3.77, 
                4.51
                ], 
                [
                "swept", 
                4.51, 
                4.79
                ], 
                [
                "through", 
                4.79, 
                4.95
                ], 
                [
                "Colorado", 
                4.95, 
                5.59
                ], 
                [
                "on", 
                5.59, 
                5.73
                ], 
                [
                "Sunday", 
                5.73, 
                6.35
                ]
            ]
            }
        ], 
        "final": 50
        }
    ], 
    "result_index": 0
    }
    '''

<<<<<<< HEAD:api/backend/services/stringconvert.py
# data = json.loads(result)
=======
data = json.loads(result2)
>>>>>>> 54d6ed2d3a849d2275d04c94495269cee525f405:api/backend/stringconvert.py

def convert(data) :
    entirestring = ''

<<<<<<< HEAD:api/backend/services/stringconvert.py
    for x in data['results']: 
        for y in x['alternatives']:
            entirestring = y["transcript"]
    return entirestring.lower().split("next question")
    
=======
    for x in d['results']: 
        for y in x['alternatives']:
            entirestring += y["transcript"]
    arr = entirestring.lower().split("next question")
    finalarr = []
    for x in arr :
        temp = ''
        words = x.split()
        for w in words :
            if w == 'ibm' or w == 'yourself' or w == 'strengths' or w == 'job' :
                temp += w
                qa = {}
                qa['question'] = temp
                finalarr.append(qa)
                temp = ''
            else :
                temp += w + " "
        qa = {}
        qa['answer'] = temp
        finalarr.append(qa)
            
    return finalarr
            

            



>>>>>>> 54d6ed2d3a849d2275d04c94495269cee525f405:api/backend/stringconvert.py

# print convert(data)

        
    

